services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    image: ${APP_NAME}-api:dev
    container_name: ${APP_NAME}-api
    env_file:
      - path: apps/api/.env-docker
        required: true
      - path: apps/api/.env-local
        required: false
    ports:
      - '3333:3333'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./package.json:/app/package.json:ro
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml:ro
      - ./tsconfig.base.json:/app/tsconfig.base.json:ro
      - ./libs:/app/libs
      - ./apps/api:/app/apps/api
    restart: unless-stopped
    networks:
      - app-net
    command: ['pnpm', '--filter', './apps/api', 'dev']

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
      args:
        NEXT_PUBLIC_BASE_PATH:
        NEXT_PUBLIC_APP_API_URL: ${APP_API_URL}
        NEXT_PUBLIC_APP_FRONT_URL: ${APP_FRONT_URL}
        NEXT_PUBLIC_APP_ADMIN_URL: ${APP_ADMIN_URL}
        SERVER_APP_API_URL: http://${APP_NAME}-api:3333
    image: ${APP_NAME}-web:dev
    container_name: ${APP_NAME}-web
    environment:
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_BASE_PATH:
      NEXT_PUBLIC_APP_API_URL: ${APP_API_URL}
      NEXT_PUBLIC_APP_FRONT_URL: ${APP_FRONT_URL}
      NEXT_PUBLIC_APP_ADMIN_URL: ${APP_ADMIN_URL}
      SERVER_APP_API_URL: http://${APP_NAME}-api:3333
    volumes:
      - .:/app
      - web-node-modules:/app/node_modules
      - web-app-node-modules:/app/apps/web/node_modules
      - web-packages-types-node-modules:/app/packages/types/node_modules
      - web-packages-utils-node-modules:/app/packages/utils/node_modules
      - web-packages-react-shared-node-modules:/app/packages/react-shared/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - app-net
    command: ['pnpm', '--filter', './apps/web', 'dev']

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile.dev
      args:
        VITE_API_URL: ${APP_API_URL}
        VITE_FRONT_URL: ${APP_FRONT_URL}
        VITE_ADMIN_URL: ${APP_ADMIN_URL}
    image: ${APP_NAME}-admin:dev
    container_name: ${APP_NAME}-admin
    environment:
      VITE_API_URL: ${APP_API_URL}
      VITE_FRONT_URL: ${APP_FRONT_URL}
      VITE_ADMIN_URL: ${APP_ADMIN_URL}
    volumes:
      - .:/app
      - admin-node-modules:/app/node_modules
      - admin-app-node-modules:/app/apps/admin/node_modules
      - admin-packages-types-node-modules:/app/packages/types/node_modules
      - admin-packages-utils-node-modules:/app/packages/utils/node_modules
      - admin-packages-react-shared-node-modules:/app/packages/react-shared/node_modules
    ports:
      - '4200:4200'
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - app-net
    command: ['pnpm', '--filter', './apps/admin', 'dev']

networks:
  app-net:
    name: ${APP_NAME}-net
    driver: bridge

volumes:
  api-node-modules:
  api-app-node-modules:
  api-packages-types-node-modules:
  api-packages-utils-node-modules:
  api-packages-react-shared-node-modules:
  web-node-modules:
  web-app-node-modules:
  web-packages-types-node-modules:
  web-packages-utils-node-modules:
  web-packages-react-shared-node-modules:
  admin-node-modules:
  admin-app-node-modules:
  admin-packages-types-node-modules:
  admin-packages-utils-node-modules:
  admin-packages-react-shared-node-modules:
