/* eslint-disable */
// This file is auto-generated by scripts/generate-config.mjs.
// Do not edit this file directly. Update config/app.yml instead.

export const appConfig = {
    "app": {
        "name": "ACK Platform",
        "description": "Full-stack starter for Nest, Vite, and Next"
    },
    "branding": {
        "primaryColor": "#0B5CF1",
        "secondaryColor": "#1BC5BD",
        "logo": "/assets/logo.svg"
    },
    "urls": {
        "api": "http://localhost:3333",
        "admin": "http://localhost:4200",
        "web": "http://localhost:3000",
        "cdn": ""
    },
    "features": {
        "enableSignup": true
    }
} as const;

export const runtimeConfig = {
    "apiUrl": "http://localhost:3333",
    "webUrl": "http://localhost:3000",
    "frontUrl": "http://localhost:3000",
    "adminUrl": "http://localhost:4200",
    "cdnUrl": "",
    "appName": "ACK Platform",
    "appDescription": "Full-stack starter for Nest, Vite, and Next",
    "features": {
        "enableSignup": true
    }
} as const;

export type AppConfig = typeof appConfig;
export type RuntimeConfig = typeof runtimeConfig;
