name: Sync Template Repository

on:
  schedule:
    - cron: "0 0 * * *"  # Adjust this as needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}  # Set GH_TOKEN from the PAT_GITHUB_TOKEN secret

    steps:
      # Step 2: Set dynamic branch name with the current date
      - name: Set Dynamic Branch Name
        id: vars
        run: echo "BRANCH_NAME=update-from-template-$(date +'%Y-%m-%d')" >> $GITHUB_ENV


       # Step 2: Checkout the project repository using SSH
      - name: Checkout Project Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB_TOKEN }}

      # Step 3: Fetch the template repository and checkout its main branch
      - name: Fetch Template Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add template https://github.com/ack-solutions/nest-react-next.git
          git fetch template main
          git checkout -b "${{ env.BRANCH_NAME }}" template/main
          git log -3 --oneline
          git push -u origin HEAD --force

      # Step 5: Create a Pull Request
      - name: Create Pull Request
        run: |
          gh pr create \
            --title "Update from Template Repository" \
            --body "This PR includes the latest changes from the template repository." \
            --head "${{ env.BRANCH_NAME }}" \
            --base main